### PR TITLE
Migration to null-safety

### PR DESCRIPTION
**Pull request by mk-dev-1**
Hi all,

I have put together an initial PR for migrating the package to null-safety. However, I can't seem to find a way to migrate the package in a way that this

```dart
late RxCommand<void, void> myCommand;

[...]

RxCommand.createSyncNoParamNoResult(_myFunc)

[...]

void _myFunc() {}

[...]

myCommand();
myCommand.execute();
```

It's related to these two lines:

```dart
  /// Calls the wrapped handler function with an option input parameter
  void execute(TParam param);

  /// This makes RxCommand a callable class, so instead of `myCommand.execute()` you can write `myCommand()`
  void call(TParam param) => execute(param);
```

which used to be

```dart
  /// Calls the wrapped handler function with an option input parameter
  void execute([TParam param]);

  /// This makes RxCommand a callable class, so instead of `myCommand.execute()` you can write `myCommand()`
  void call([TParam param]) => execute(param);
```

I have therefore not updated the tests and demo application yet.

May I kindly request you to review and amend as necessary.

Thank you!

### CODE REVIEW

**Comment by mk-dev-1** [comment]
Dart seems to accept the following:

```dart
myCommand(null);
myCommand.execute(null);
```
If that's okay, I'm happy to update the tests and sample app...

**Comment by escamoteur** [comment]
> 
> 
> Dart seems to accept the following:
> 
> ```dart
> myCommand(null);
> myCommand.execute(null);
> ```
> 
> If that's okay, I'm happy to update the tests and sample app...

Hi,
this actually a place where it gets a bit tricky because you can't assign a command directly to a `VoidCallback` handler inside a Widget which kills much of the elegance of commands.

If you have the time it would be great if you could have a look at how I did the null safety migration in flutter_command.
Possibly it could make sense to adapt the rx_command API to the changes I made in flutter_command, namely that `CommandResult` looks a bit differently.

Actually without migrating the tests and the example you won't see if your changes still work in the way commands are used so far.
Thanks a lot for your help.

**Comment by mk-dev-1** [comment]
I have updated the tests and all of them pass with the proposed solution, but I do agree that it is not very elegant.

I'm happy to give your suggestion a go, but I am not sure I've got sufficient time for it (or can do it in the first place...)

**Comment by AlexBacich** [comment]
@escamoteur , @mk-dev-1 , any update on this?

**Comment by mk-dev-1** [comment]
@AlexBacich @escamoteur I'm afraid I'm not confident I can provide an update or a full solution soon - too many other things on my plate.... (just so that you guys are not waiting for me here!)

**Comment by mk-dev-1** [comment]
Cancelled as already completed.

**Pull request closed without merging**
