### PR TITLE
Bugfix/example

### PR DESCRIPTION
**Pull request by AlexBacich**
- Updated example, made it running on Android
- Minor fixes to naming

### CODE REVIEW

**Comment by escamoteur** [comment]
Thanks, looks good!
I will have to run dartfmt over it because the pub scoring substracts points if you have lines that are longer than 80 characters

**Comment by AlexBacich** [comment]
Yeah, sorry for that - I have setup my IDE for 120 lines.

**Comment by escamoteur** [comment]
I will push the new version in a moment. Have you seen that I have a new package flutter_command as an alternative?

**Comment by AlexBacich** [comment]
I haven't seen flutter_command before, thanks for pointing it out. However I will stay with RxCommand as streams seem to be better solution.

**Pull request merged**
