### PR TITLE
Rxdart 0.25.0

### PR DESCRIPTION
**Pull request by josh-ksr**
- use rxdart 0.25.0
- fixed ios project settings in example project

### CODE REVIEW

**Review by escamoteur — CHANGES_REQUESTED** [review]
Hi 

thanks a lot for fixing this!
Could you add a new enttry in the changelog and update the version in pubspec please?
Cheers Thomas

**Comment by josh-ksr** [comment]
Hi,

I've added a changelog entry with the lastest commit.
The version was already increased to 5.3.0, or is there still anything else that needs to be changed?

Regards Josh

**Comment by escamoteur** [comment]
could you imagine getting maintainer of this package?

**Comment by escamoteur** [comment]
just pushed the newe version on pub

**Comment by escamoteur** [comment]
@josh-ksr

**Comment by josh-ksr** [comment]
@escamoteur sure, if you want to add another maintainer i'd be happy to help out as i'm using the package in multiple projects.

**Comment by escamoteur** [comment]
done

**Pull request merged**
